# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

exclusive_lasso_penalty <- function(x, groups) {
    .Call('_ExclusiveLasso_exclusive_lasso_penalty', PACKAGE = 'ExclusiveLasso', x, groups)
}

exclusive_lasso_prox <- function(z, groups, lambda, lower_bound, upper_bound, thresh = 1e-7) {
    .Call('_ExclusiveLasso_exclusive_lasso_prox', PACKAGE = 'ExclusiveLasso', z, groups, lambda, lower_bound, upper_bound, thresh)
}

exclusive_lasso_gaussian_pg <- function(X, y, groups, lambda, w, o, lower_bound, upper_bound, thresh = 1e-7, thresh_prox = 1e-7, intercept = TRUE) {
    .Call('_ExclusiveLasso_exclusive_lasso_gaussian_pg', PACKAGE = 'ExclusiveLasso', X, y, groups, lambda, w, o, lower_bound, upper_bound, thresh, thresh_prox, intercept)
}

exclusive_lasso_glm_pg <- function(X, y, groups, lambda, w, o, family, lower_bound, upper_bound, thresh = 1e-7, thresh_prox = 1e-7, intercept = TRUE) {
    .Call('_ExclusiveLasso_exclusive_lasso_glm_pg', PACKAGE = 'ExclusiveLasso', X, y, groups, lambda, w, o, family, lower_bound, upper_bound, thresh, thresh_prox, intercept)
}

exclusive_lasso_gaussian_cd <- function(X, y, groups, lambda, w, o, lower_bound, upper_bound, thresh = 1e-7, intercept = TRUE) {
    .Call('_ExclusiveLasso_exclusive_lasso_gaussian_cd', PACKAGE = 'ExclusiveLasso', X, y, groups, lambda, w, o, lower_bound, upper_bound, thresh, intercept)
}

exclusive_lasso_glm_cd <- function(X, y, groups, lambda, w, o, family, lower_bound, upper_bound, thresh = 1e-7, thresh_prox = 1e-7, intercept = TRUE) {
    .Call('_ExclusiveLasso_exclusive_lasso_glm_cd', PACKAGE = 'ExclusiveLasso', X, y, groups, lambda, w, o, family, lower_bound, upper_bound, thresh, thresh_prox, intercept)
}

calculate_exclusive_lasso_df <- function(X, lambda_vec, groups, coefs) {
    .Call('_ExclusiveLasso_calculate_exclusive_lasso_df', PACKAGE = 'ExclusiveLasso', X, lambda_vec, groups, coefs)
}

